spring.application.name=scoot-app-bff

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://overylord:aiQXeXJaPNuhStvG@cluster0.cnfpvzy.mongodb.net/}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:scoot-app}

# Server Configuration
server.port=${PORT:8080}
server.address=0.0.0.0

# Logging
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
logging.level.com.kotlin_spring_mongodb=DEBUG

# Database Management
app.database.clear-on-startup=${APP_DATABASE_CLEAR_ON_STARTUP:true}
