spring.application.name=scoot-app-be

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://overylord:aiQXeXJaPNuhStvG@cluster0.cnfpvzy.mongodb.net/
spring.data.mongodb.database=scoot-app

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
logging.level.com.kotlin_spring_mongodb=DEBUG

# Database Management
# Set to true to clear database on startup
app.database.clear-on-startup=true

